### ISSUE TITLE
Server side resuming

### ISSUE THREAD

**Issue by scwgoire** [igolaizola/resumetls#1]
Hi @igolaizola,

6 years later, it's been a while 😄 

I naively tried to change `tls.Client()` to `tls.Server()` (in both `clientInitialize` and `clientResume`) as my use case is transferring open sockets from a server app to an updated instance of it. Then I did as written in the README. Of course it failed (error: `local error: tls: bad record MAC`).

I have very little knowledge about TLS and its Go implementation, do you think there is a possibility to achieve that ? What would it take ?

Thank you very much!

For reference, here is my relevant portion of code
```
	conn, err := lis.Accept()
	if err != nil {
		panic(err)
	}

	cl, err := resume_tls.Client(conn, config, nil)
	if err != nil {
		panic(err)
	}
	cl.Handshake()

	state := cl.State()
	cli, err := resume_tls.Client(conn, config, state)
	if err != nil {
		panic(err) <--- panics here with the error above
	}
```

**Comment by igolaizola** [comment]
It definitely has been a while! My oldest child is the same age now!

I have uploaded a fix/workaround for the client-side part. It wasn't working with the latest Golang version due to how random bytes are consumed when elliptic curve keys are generated.

I've added the code for the server-side part, adapting the client-side code (similar to what you did), but it is not working yet.
I will try to take a deeper look.

**Comment by igolaizola** [comment]
@scwgoire I fixed it!

Golang's TLS handshake key generation uses internally `randutil.MaybeReadByte` which randomly reads one byte from the Rand reader. This makes the bytes used by handshake process non-deterministic.
To avoid this, I have overriden the state Rand buffer to avoid writing or reading from it when only one byte is needed.

Here is the commit that fixes it: https://github.com/igolaizola/resumetls/commit/a5ae86de46e736c78f62097cfdea5aa058396934

I also renamed the package and the project from `resume-tls` to `resumetls` (I hate hyphens in package names).

**Comment by scwgoire** [comment]
Iñigo, you are amazing! Jumping that fast so many years after last commit... I'm impressed! 😮 

I gave it a try, but it still didn't solve the issue. Same error appears. I suspect this may be due to how different ciphers need different material to work. I'll try to dig deeper later on.

Here is my code (`cert` and `key` containing certificate/key data)
```
package main

import (
	"crypto/tls"
	"fmt"
	"net"

	"github.com/igolaizola/resumetls"
)

func main() {
	pair, err := tls.X509KeyPair([]byte(cert), []byte(key))
	if err != nil {
		panic(err)
	}

	config := &tls.Config{
		Certificates:       []tls.Certificate{pair},
		InsecureSkipVerify: true,
	}

	lis, err := net.Listen("tcp", "localhost:2000")
	if err != nil {
		panic(err)
	}

	conn, err := lis.Accept()
	if err != nil {
		panic(err)
	}

	fmt.Println("Connection accepted from", conn.RemoteAddr())
	cl, err := resumetls.Server(conn, config, nil)
	if err != nil {
		panic(err)
	}
	err = cl.Handshake()
	if err != nil {
		panic(err)
	}
	cl.Write([]byte("Hello world!"))
	state := cl.State()

	cli, err := resumetls.Server(conn, config, state)
	if err != nil {
		panic(err)
	}
	cl.Write([]byte("Welcome back darling!"))
	cli.Close()
}
```

**Comment by igolaizola** [comment]
Hi again, @scwgoire.

I have updated the tests, and now they are passing on both the client and server for all available cipher suites. Could you try explicitly specifying the cipher suite in the TLS configuration? It could be something related with that.

**Comment by igolaizola** [comment]
I've just uploaded a fix that shoud make it work even without specifying a cipher suite.

https://github.com/igolaizola/resumetls/commit/a253f5cca5eb6567e7edecc9da194761edc22803

The negotiated cipher suite is now persisted in the state and then restored on resumption.

**Comment by scwgoire** [comment]
Iñigo, thanks again for spending some time to get there!

Unfortunately, this doesn't work either. When calling `resumetls.Server()`, the TLS stack acts like the TLS negociation hasn't been done and tries to perform another handshake instead of just keep going on with the current keying material, is this expected?

I just ran the code above (with the proper `cert` and `key` variables) and issued an `openssl s_client -connect localhost:2000` in my term.

This is the call stack where the error is produced (I stopped digging at the `decrypt` level, this indicates the keying material is not good).

```
tls.(*Conn).readRecordOrCCS (conn.go:686) crypto/tls
tls.(*Conn).retryReadRecord (conn.go:791) crypto/tls
tls.(*Conn).readRecordOrCCS (conn.go:750) crypto/tls
tls.(*Conn).readRecord (conn.go:588) crypto/tls
tls.(*Conn).readHandshakeBytes (conn.go:1075) crypto/tls
tls.(*Conn).readHandshake (conn.go:1086) crypto/tls
tls.(*serverHandshakeStateTLS13).readClientFinished (handshake_server_tls13.go:979) crypto/tls
tls.(*serverHandshakeStateTLS13).handshake (handshake_server_tls13.go:81) crypto/tls
tls.(*Conn).serverHandshake (handshake_server.go:53) crypto/tls
<autogenerated>:2
tls.(*Conn).handshakeContext (conn.go:1553) crypto/tls
tls.(*Conn).HandshakeContext (conn.go:1493) crypto/tls
tls.(*Conn).Handshake (conn.go:1477) crypto/tls
resumetls.resume (resumetls.go:117) github.com/igolaizola/resumetls
resumetls.newConn (resumetls.go:48) github.com/igolaizola/resumetls
resumetls.Server (resumetls.go:42) github.com/igolaizola/resumetls
main.main (rtls.go:57) main
runtime.main (proc.go:271) runtime
runtime.goexit (asm_arm64.s:1222) runtime
```

Please note I can run the tests fine. I can't see any significant difference between the `testServer` function and my code. I tried also reading from the client before dumping the state and creating the new server, no luck. I also tried to force tls1.2 on the openssl client, no luck either.
Tomorrow I'll try to do it with a golang TLS client. Just in case.

**Comment by igolaizola** [comment]
Hi @scwgoire! Yes, you're right. The server side is not working properly.
I have confirmed it implementing some manual end to end tests that use OpenSSL.

Check this: https://github.com/igolaizola/resumetls/tree/main/cmd/e2e

We need to figure out what we're missing in the resumed TLS connection and see if it is a field that can be restored using reflection.
